version: '3.3'
services:
  lab1:
    container_name: lab1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    volumes:
      - ./src/mr:/mr
    networks:
      - network
    command: /bin/bash -c "cd main && bash test-mr.sh"
  lab3:
    container_name: lab3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./report:/mit6.824/report
    networks:
      - network
    environment:
      debug: "false"
    command: /bin/bash -c "cd src/raft && time go test > /mit6.824/report/test1.log"
networks:
  network: